spring:
  application:
    name: thinking-in-langchain
  profiles:
    active: dev

server:
  port: 8080

langchain4j:
  community:
    dashscope:
      streaming-chat-model:
        api-key: ${DASHSCOPE_APIKEY}
        model-name: qwen-plus
      chat-model:
        api-key: ${DASHSCOPE_APIKEY}
#        模型列表：https://help.aliyun.com/zh/model-studio/models
#        model-name: deepseek-v3
        model-name: qwen-plus
#        base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
