server:
  port: 8000
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:postgresql://172.29.12.5:5433/springai
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 60
      minimum-idle: 5
      connection-test-query: SELECT 1
      connection-init-sql: SELECT 1


langchain4j:
#  community:
#    dashscope:
#      chat-model:
#        api-key: ${DASHSCOPE_APIKEY}
#        #model-name: deepseek-v3
#        #model_name: qwen-max
#        model-name: qwen-max-latest
  ollama:
    chat-model:
      base-url: http://172.29.12.5:11434
      #model-name: llama3.1
      model-name: llava
    embedding-model:
      base-url: http://172.29.12.5:11434
      model-name: all-minilm



pgvector:
  database: springai
  host: 172.29.12.5
  port : 5433
  user: postgres
  password: postgres
  table: my_embeddings

search:
  apiKey: ${SEARCH_APIKEY}
  engine: baidu

